GameSceneUIで制限時間表示用バーを追加
tricore-as16/KONAMI_CONTEST_Project pull request #18
Opened 2024-06-19 00:40 UTC by tricore-as16

・GameSceneUIでGemWaveStateと、waveConstantsTableを確認しウェーブごとの制限時間に応じて、
　制限時間用のバーを動かすように修正。
・UIの位置の設定
・すいません。学校で作品公表会があるためこのブランチ内でプレイヤー操作とシーン移行操作をパッド対応させました。

2024-06-19 01:01 UTC, tricore-as03 requested changes

2024-06-19 01:01 UTC, tr-t-mitsumaru commented on Camera.cpp
> +	//SetCameraPositionAndTarget_UpVecY(pos, VGet(-7, 5, 20));
[MUST]
不要であれば消してください。

2024-06-19 01:01 UTC, tr-t-mitsumaru commented on GameSceneUI.cpp
> +        DrawFormatString(100, 100, UI_COLOR, "ウェーブ１：宝石との出会い");
[MUST]
このウェーブごとの文字列も`WaveConstants`にまとめてしまってよいかと。
GameSceneクラスから、今のウェーブの`WaveConstants`を引数で受けとるようにすれば、この関数のswitch自体が不要になるかと。

2024-06-19 01:02 UTC, tricore-as16 commented on Camera.cpp
> +	//SetCameraPositionAndTarget_UpVecY(pos, VGet(-7, 5, 20));
すいません。承知しました。

2024-06-19 01:03 UTC, tricore-as16 commented on GameSceneUI.cpp
> +        DrawFormatString(100, 100, UI_COLOR, "ウェーブ１：宝石との出会い");
承知しました。修正試してみます。

2024-06-19 01:04 UTC, tricore-as16 commented on GameSceneUI.cpp
> +        DrawFormatString(100, 100, UI_COLOR, "ウェーブ１：宝石との出会い");
ありがとうございます！了解しました！修正試してみます。

2024-06-19 01:21 UTC, tricore-as16 commented on Camera.cpp
> +	//SetCameraPositionAndTarget_UpVecY(pos, VGet(-7, 5, 20));
修正しました。

2024-06-19 01:23 UTC, tricore-as16 commented on GameSceneUI.cpp
> +        DrawFormatString(100, 100, UI_COLOR, "ウェーブ１：宝石との出会い");
学校で作品審査会があるため、あと回しで対応させていただきたいと思います。
6/21(金)に対応予定です。

2024-06-20 15:40 UTC, tricore-as16 commented on GameSceneUI.cpp
> +        DrawFormatString(100, 100, UI_COLOR, "ウェーブ１：宝石との出会い");
string型だったものをDxlibの文字列関数に合わせるためにChar* に変更し、GameSceneUIに渡して表示するように変更しました。

2024-06-21 01:59 UTC, tricore-as03 approved these changes
LGTM

2024-06-21 02:32 UTC, merged