GameSceneUIの追加、スコアをSceneごとに引き渡し
tricore-as16/KONAMI_CONTEST_Project pull request #19
Opened 2024-06-20 03:56 UTC by tricore-as16

・GameSceneの残り時間が少なくなったことを知らせるUIを作成
・スコア、ハイスコアを各Sceneのコンストラクタで引き渡し

2024-06-20 04:09 UTC, tricore-as03 requested changes

2024-06-20 04:09 UTC, tricore-as03 commented on ClearScene.cpp
> +        return new MenuScene(score,highScore);
[Q]
以前、口頭で聞いた際に`MenuScene`ではハイスコアのみを表示しているとのことでしたが、`score`の値も必要なのでしょうか？
`GameScene`か`MenuScene`あたりで`score`と`highscore`を比較し、大きいほうをハイスコアとして`MenuScene`に渡してしまえばよいと思うのですが。

2024-06-20 04:09 UTC, tricore-as03 commented on UIGraph.h
> +class UIGraph
[MUST]
`UIGraph`とはどういったUIでしょうか？
もう少し具体的な名前を付けて欲しいです。

2024-06-20 15:17 UTC, tricore-as16 commented on ClearScene.cpp
> +        return new MenuScene(score,highScore);
おっしゃる通りで、MenuSceneではscoreは必要ないのでコンストラクタ引数から削除しました。

2024-06-20 15:19 UTC, tricore-as16 commented on UIGraph.h
> +class UIGraph
UIGraphはUIの画像を移動させたいときVECTOR情報を持たせたいと考えたためObjectのような、ポジションと画像ハンドルを持ったUI専用のクラスにしたいと考えたためUIObjectクラスに名前を変更したのですが、もっと具体的なUIObjectMoveGraphのようにした方がよいでしょうか？

2024-06-21 02:08 UTC, tricore-as03 commented on UIGraph.h
> +class UIGraph
[MUST]
`Graph`や`Object`は名前の意味合いが広く、実際の処理の内容を推測しづらいので避けるべきです。
恐らく、DxLibの関数が`xxxGraph`なのでそれに引っ張られたんだとは思いますが。
詳細を口頭で伺います。

2024-06-21 06:37 UTC, tricore-as16 commented on UIGraph.h
> +class UIGraph
UIGraphをTranslationlStartPositionに変更し、画面に入ってくる関数をと、画面から出ていく関数を作成しました。

2024-06-21 08:11 UTC, tricore-as16 commented on UIGraph.h
> +class UIGraph
TimeLimitUIAnimationの動作をUpdateとDrawに分けてGameSceneUIのなかで呼ぶように変更しました

2024-06-21 08:18 UTC, tricore-as03 requested changes

2024-06-21 08:18 UTC, tricore-as03 commented on TimeLimitUIAnimation .h
> +class TimeLimitUIAnimation
[MUST]
クラス名もTimeLimitsWarningUIに修正をお願いします。

2024-06-21 08:18 UTC, tricore-as03 commented on TimeLimitUIAnimation .cpp
> +        if (position.x >= 1200)
[MUST]
このへんの値は定数にしてください。
`DrawFormatString`に渡してる`120`や`30`は調整を表す`OffsetPosition`とかでいいと思います。

2024-06-23 04:36 UTC, tricore-as16 commented on TimeLimitUIAnimation .h
> +class TimeLimitUIAnimation
承知しました！専用のクラスなのに変数名を同じにしていませんでした。すいません。

2024-06-23 04:49 UTC, tricore-as16 commented on TimeLimitUIAnimation .cpp
> +        if (position.x >= 1200)
承知しました。定数化行いました！

2024-06-24 07:14 UTC, tricore-as03 requested changes
LGTM

2024-06-24 07:14 UTC, tricore-as03 commented on TimeLimitsWarningUI.cpp
> +}
[MUST]
不要であれば削除してください。

2024-06-24 07:14 UTC, tricore-as03 commented on TimeLimitsWarningUI.h
> +    void TranslationTargetPosition(int timerLimit);
[MUST]
TimeLimitsWarningUIのUpdate内でしか使ってないようなのでprivateで良いかと。

2024-06-24 08:03 UTC, tricore-as16 commented on TimeLimitsWarningUI.cpp
> +}
承知しました。不要なため削除しました。

2024-06-24 08:05 UTC, tricore-as16 commented on TimeLimitsWarningUI.h
> +    void TranslationTargetPosition(int timerLimit);
承知しました。privateに移動させました！

2024-06-25 00:41 UTC, tricore-as03 approved these changes
LGTM

2024-06-25 01:08 UTC, merged