追加したモデルの関数を実装
tricore-as16/KONAMI_CONTEST_Project pull request #22
Opened 2024-06-28 03:05 UTC by tricore-as16

・プレイヤーアニメーション実装
・オールのアニメーション作成、実装
・当たり判定をもともとプレイヤー座標基準だったものを、クッションの座標基準に変更しました

2024-06-28 03:10 UTC, tricore-as16 commented
モデル変更後のゲーム画面です。
![Uploading スクリーンショット 2024-06-28 120156.png…]()

2024-06-28 03:36 UTC, tricore-as07 requested changes

2024-06-28 03:36 UTC, tricore-as07 commented on StageManager.h
> +class StageManager
[MUST]
Managerという名前はあまり乱用するべきではないので、
StageObjectsやStageObjectSetなどの名前がいいと思います。

2024-06-28 03:36 UTC, tricore-as07 commented on SkyDome.cpp
> +	: modelHandle	    (-1)
[MUST]
こういうところのインデントや空白は揃えるのであれば
ちゃんと揃えましょう

2024-06-28 03:36 UTC, tricore-as07 commented on Player.cpp
> +        dir = VAdd(dir, VGet(-1, 0, 0));
[MUST]
移動方向のベクトルは定数として宣言して名前を付けたほうがわかりやすいです

2024-06-28 04:18 UTC, tricore-as16 commented on StageManager.h
> +class StageManager
承知しました。
StageObjectSetに変更します！

2024-06-28 04:29 UTC, tricore-as16 commented on Player.cpp
> +        dir = VAdd(dir, VGet(-1, 0, 0));
承知しました。変更します！

2024-06-28 04:37 UTC, tricore-as16 commented on SkyDome.cpp
> +	: modelHandle	    (-1)
承知しました。
すいません、自分のコード上だと最初からインデントがそろっているのですが、どうすればいいでしょうか？

2024-06-28 04:43 UTC, tricore-as07 commented on SkyDome.cpp
> +	: modelHandle	    (-1)
おそらくインデントでTabを使って空白を作っていることが原因だと思うので
すべて半角スペースに置き換えてください。
一応コーディングルールにも記載があるのでどこかタイミングを見てすべての空白を置き換える作業をお願いします。
https://github.com/tricore-t-yui/tricore-wiki/wiki/Unity%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F%E9%96%8B%E7%99%BA%E6%99%82%E3%81%AEC%23%E3%82%B3%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB#%E3%82%A4%E3%83%B3%E3%83%87%E3%83%B3%E3%83%88

2024-06-28 06:28 UTC, tricore-as16 commented on SkyDome.cpp
> +	: modelHandle	    (-1)
今回のプルリクのみ修正しました。

2024-07-01 00:34 UTC, tricore-as07 requested changes

2024-07-01 00:34 UTC, tricore-as07 commented on Player.cpp
> +    ,   width                   (HIT_BOX_WIDTH)
[MUST]
ここのインデントがまだずれているので修正をお願いします

2024-07-01 01:21 UTC, tricore-as07 approved these changes
LGTM

2024-07-01 01:22 UTC, merged