ゲームシーンのチュートリアルの修正
tricore-as16/KONAMI_CONTEST_Project pull request #30
Opened 2024-07-08 01:26 UTC by tricore-as16

・クッションに宝石を当てて跳ね返すこと、宝箱に入れることを強調したかったため、矢印を追加
・チュートリアル画像を追加

2024-07-08 07:36 UTC, tricore-as03 requested changes

2024-07-08 07:36 UTC, tricore-as03 commented on TutorialStateInformation.h
[Q]
このクラスを作った意図はなんでしょうか？
画像ハンドルを持っているだけのようですが。

2024-07-08 08:40 UTC, tricore-as16 commented on TutorialStateInformation.h
すいません。今後チュートリアル画像の位置を移動させたりすることになった場合、座標情報や、チュートリアルで説明する用の文字列を格納したいと考えてクラス化しました。
しかし、画像を移動させたりするのは想定以上に時間がかかる思い、あとマスター期限まで数日しかなかったためこの実装内容でプルリクエストを送信させていただきました。

2024-07-08 10:55 UTC, tricore-as03 requested changes

2024-07-08 10:55 UTC, tricore-as03 commented on TutorialStateInformation.h
了解です。
であれば、その旨をTODOコメントで書いてください。

2024-07-09 00:54 UTC, tricore-as16 commented on TutorialStateInformation.h
承知しました。
TODOコメント追加しました。

2024-07-09 00:59 UTC, tricore-as03 approved these changes
LGTM

2024-07-09 01:05 UTC, merged